import esbuild from "esbuild";
import sveltePlugin from "esbuild-svelte";
import autoPreprocess from "svelte-preprocess";
import process from "process";

const banner = 
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugin's GitHub repository (https://github.com/MichelleGDyason/obsidian-dictionary-plus)
*/
`;

const prod = process.argv[2] === 'production';
const options = {
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: ['obsidian'],
    format: 'cjs',
    minify: prod,
    target: 'es2020',
    logLevel: "info",
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    plugins: [sveltePlugin({
        compilerOptions: {
            css: "injected",
            dev: !prod,
        },
        preprocess: autoPreprocess(),
    })],
    outfile: 'main.js',
};

if (prod) {
    await esbuild.build(options);
} else {
    const context = await esbuild.context(options);
    await context.watch();
}
