import { RFC } from './_constants';
import type { DictionaryWord } from "src/integrations/types";
import type DictionaryPlugin from "src/main";
import type { DictionarySettings } from "src/types";

import t from "src/l10n/helpers";
import { MarkdownView, Modal, normalizePath, Notice, TFile } from "obsidian";
import { buildFlashcardEntry } from "./flashcards";

//This really needs a refactor

export default class LocalDictionaryBuilder {
    plugin: DictionaryPlugin;
    settings: DictionarySettings;

    constructor(plugin: DictionaryPlugin) {
        this.plugin = plugin;
        this.settings = plugin.settings;
    }

    private cap(string: string): string {
        if (string) {
            const words = string.split(" ");

            return words.map((word) => {
                return word[0].toUpperCase() + word.substring(1);
            }).join(" ");
        }
        return string;
    }

    async newNote(content: DictionaryWord, openNote = true): Promise<void> {

        const { plugin, settings } = this;

        let audioLinks = '';
        content.phonetics.forEach((value, i, a) => {
            if (value.audio) {
                audioLinks += '- ' + (value.audio.startsWith("http") ? value.audio : "https:" + value.audio);
                if (i != a.length - 1) {
                    audioLinks += '\n';
                }
            }
        });

        let phonetics = '';
        content.phonetics.forEach((value, i, a) => {
            if (value.text) {
                phonetics += '- ' + (value.audio ? `<details><summary>${value.text}</summary><audio controls><source src="${value.audio.startsWith("http") ? value.audio : "https:" + value.audio}"></audio></details>` : value.text);
                if (i != a.length - 1) {
                    phonetics += '\n';
                }
            }
        });

        let meanings = '';
        content.meanings.forEach((value, i) => {
            meanings += '### ' + this.cap(value.partOfSpeech ?? t("Meaning {{i}}").replace(/{{i}}/g, (i + 1).toString())) + '\n\n';
            value.definitions.forEach((def, j, b) => {
                meanings += def.definition + '\n\n';
                if (def.example) {
                    meanings += '> ' + def.example + '\n\n';
                }
                if (def.synonyms && def.synonyms.length != 0) {
                    def.synonyms.forEach((syn, i, a) => {
                        meanings += syn;
                        if (i != a.length - 1) {
                            meanings += ', ';
                        }
                    })
                    meanings += '\n\n'
                }
                if (j != b.length - 1) {
                    meanings += '---\n\n';
                }
            });
        });

        let file: TFile;
        const langString = RFC[settings.defaultLanguage];
        const path = `${settings.folder ? settings.folder + '/' : ''}${settings.languageSpecificSubFolders ? langString + '/' : ''}${settings.prefix.replace(/{{lang}}/ig, langString)}${settings.capitalizedFileName ? this.cap(content.word) : content.word}${settings.suffix.replace(/{{lang}}/ig, langString)}.md`;
        let contents = settings.template
            .replace(/{{notice}}/ig, t('Autogenerated by Obsidian Dictionary Plugin'))
            .replace(/{{word}}/ig, settings.capitalizedFileName ? this.cap(content.word) : content.word)
            .replace(/{{pronunciationheader}}/ig, t('Pronunciation'))
            .replace(/{{phoneticlist}}/ig, phonetics)
            .replace(/{{meaningheader}}/ig, t('Meanings'))
            .replace(/{{meanings}}/ig, meanings)
            .replace(/{{lang}}/ig, langString)
            .replace(/{{audioLinks}}/ig, audioLinks);

        if (content.origin) {
            contents = contents
                .replace(/{{originHeader}}/ig, t('Origin'))
                .replace(/{{origin}}/ig, content.origin);
        } else {
            contents = contents
                .replace(/{{originHeader}}/ig, '')
                .replace(/{{origin}}/ig, '');
        }

        const normalizedPath = normalizePath(path);
        const existingFile = plugin.app.vault.getAbstractFileByPath(normalizedPath);
        if (existingFile instanceof TFile) {
            new OverwriteModal(this.plugin, normalizePath(path), contents, openNote).open();
            return;
        }

        try {
            await this.ensureParentFolders(normalizedPath);
            file = await plugin.app.vault.create(normalizedPath, contents);
            if (openNote) {
                await this.openFile(file);
            }
        } catch (error) {
            console.error('Failed to create dictionary note', error);
            new Notice(`Could not create dictionary note: ${this.errorMessage(error)}`);
        }
    }

    async recordLookup(content: DictionaryWord): Promise<void> {
        if (!this.settings.saveLookupHistory) return;

        const path = this.getLookupHistoryPath();
        const language = RFC[this.settings.defaultLanguage];
        const entry = buildFlashcardEntry(content, language);
        if (!entry) return;

        try {
            await this.ensureParentFolders(path);
            const existing = this.plugin.app.vault.getAbstractFileByPath(path);
            if (!existing) {
                await this.plugin.app.vault.create(
                    path,
                    `# Dictionary lookup flashcards\n\n#flashcards\n\n${entry.markdown}`
                );
                return;
            }
            if (!(existing instanceof TFile)) {
                throw new Error(`A folder already exists at ${path}`);
            }

            const current = await this.plugin.app.vault.read(existing);
            if (!current.includes(entry.marker)) {
                const separator = current.endsWith('\n') ? '\n' : '\n\n';
                await this.plugin.app.vault.modify(existing, `${current}${separator}${entry.markdown}`);
            }
        } catch (error) {
            console.error('Failed to save dictionary lookup history', error);
            new Notice(`Could not save dictionary lookup history: ${this.errorMessage(error)}`);
        }
    }

    async openLookupHistory(): Promise<void> {
        const path = this.getLookupHistoryPath();
        try {
            await this.ensureParentFolders(path);
            let file = this.plugin.app.vault.getAbstractFileByPath(path);
            if (!file) {
                file = await this.plugin.app.vault.create(
                    path,
                    '# Dictionary lookup flashcards\n\n#flashcards\n'
                );
            }
            if (!(file instanceof TFile)) {
                throw new Error(`A folder already exists at ${path}`);
            }
            await this.openFile(file);
        } catch (error) {
            console.error('Failed to open dictionary lookup history', error);
            new Notice(`Could not open dictionary lookup history: ${this.errorMessage(error)}`);
        }
    }

    private getLookupHistoryPath(): string {
        const configuredPath = this.settings.lookupHistoryPath.trim() || 'Dictionary/Lookup history.md';
        return normalizePath(configuredPath.toLowerCase().endsWith('.md')
            ? configuredPath
            : `${configuredPath}.md`);
    }

    private async ensureParentFolders(filePath: string): Promise<void> {
        const segments = normalizePath(filePath).split('/').slice(0, -1);
        let currentPath = '';

        for (const segment of segments) {
            currentPath = currentPath ? `${currentPath}/${segment}` : segment;
            const existing = this.plugin.app.vault.getAbstractFileByPath(currentPath);
            if (!existing) {
                await this.plugin.app.vault.createFolder(currentPath);
            } else if (existing instanceof TFile) {
                throw new Error(`A file blocks the folder ${currentPath}`);
            }
        }
    }

    private async openFile(file: TFile): Promise<void> {
        const leaf = this.plugin.app.workspace.getLeaf(true);
        await leaf.openFile(file);
        this.plugin.app.workspace.setActiveLeaf(leaf);
    }

    private errorMessage(error: unknown): string {
        return error instanceof Error ? error.message : String(error);
    }
}

class OverwriteModal extends Modal {
    path: string;
    content: string;
    openNote: boolean;

    constructor(plugin: DictionaryPlugin, path: string, content: string, openNote: boolean) {
        super(plugin.app);
        this.path = path;
        this.content = content;
        this.openNote = openNote;
    }

    onOpen() {
        this.contentEl.appendChild(createEl("p", { text: t("A existing File with the same Name was found, do you want to overwrite it?"), cls: "dictionarycenter" }));
        const buttonDiv = this.contentEl.appendChild(createDiv({ cls: "dictionarybuttons" }))
        buttonDiv.appendChild(createEl("button", { text: t("Yes, overwrite the old File."), cls: "mod-cta" })).onClickEvent(async () => {
            this.app.vault.modify(this.app.vault.getAbstractFileByPath(this.path) as TFile, this.content);
            let oldPaneOpen = false;
            this.app.workspace.iterateAllLeaves((leaf) => {
                if (leaf.view instanceof MarkdownView) {
                    if ((leaf.getViewState().state.file as string).endsWith(this.path)) {
                        oldPaneOpen = true;
                        this.app.workspace.setActiveLeaf(leaf);
                    }
                }
            });
            if (!oldPaneOpen && this.openNote) {
                const leaf = this.app.workspace.getLeaf(true);
                await leaf.openFile(this.app.vault.getAbstractFileByPath(this.path) as TFile);
                this.app.workspace.setActiveLeaf(leaf);
            }
            this.close();
        });
        buttonDiv.appendChild(createEl("button", { text: t("No, keep the old File."), cls: "mod-cta" })).onClickEvent(() => {
            this.close();
        });
    }
}
